apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: /
  newName: /
- name: 686710509719.dkr.ecr.ap-northeast-2.amazonaws.com/team-4
  newTag: front-d1775bd6c54e8bb923a11a197bd50f3b45171a55
- name: client-app
  newTag: main-3abede514e69bf831c9b14e42ca62ff7f179687a
- name: kkanbustock
  newTag: main-f70f4538f95eb08343161647279571c2fdbdb250
resources:
- ../../resources
